Repository neurodata/df-dn-paper, pull requests merged in 2021-05, with the labels that each got.

#12 Benchmarks on tabular data
  tabular/cc18_figure.ipynb
  tabular/cc18_hyperparameter.py
  tabular/cc18_kappaece.py
  tabular/cc18_times.py
  tabular/metrics/cc18_all_parameters.txt
  tabular/metrics/cc18_sample_sizes.txt
  tabular/plots/cc18_experiment.png
  tabular/results/cc18_dn_ece.txt
  tabular/results/cc18_dn_kappa.txt
  tabular/results/cc18_dn_times.txt
  tabular/results/cc18_rf_ece.txt
  tabular/results/cc18_rf_kappa.txt
  tabular/results/cc18_rf_times.txt
Labels: enhancement

#17 Create LICENSE
  LICENSE
Labels: documentation

#19 Add package requirements
  requirements.txt
Labels: documentation

#20 Separate tabular wall times and update experiment parameters
  tabular/cc18_figure.ipynb
  tabular/cc18_figures.ipynb
  tabular/cc18_hyperparameter.py
  tabular/cc18_kappaece.py
  tabular/cc18_times.py
  tabular/metrics/cc18_all_parameters.txt
  tabular/plots/cc18_experiment.png
  tabular/plots/cc18_scatter_plot.png
  tabular/results/cc18_dn_ece.txt
  tabular/results/cc18_dn_kappa.txt
  tabular/results/cc18_dn_times.txt
  tabular/results/cc18_dn_times_test.txt
  tabular/results/cc18_dn_times_train.txt
  tabular/results/cc18_rf_ece.txt
  tabular/results/cc18_rf_kappa.txt
  tabular/results/cc18_rf_times.txt
  tabular/results/cc18_rf_times_test.txt
  tabular/results/cc18_rf_times_train.txt
Labels: enhancement

#21 Update torch versions in requirements.txt
  requirements.txt
Labels: documentation

#23 Add package requirements for audio
  requirements.txt
Labels: documentation

#13 Conduct benchmarks for FSDD and generate figures
  .gitignore
  audio/3_class/cnn32.txt
  audio/3_class/cnn32_2l.txt
  audio/3_class/cnn32_2l_test_time.txt
  audio/3_class/cnn32_2l_train_time.txt
  audio/3_class/cnn32_5l.txt
  audio/3_class/cnn32_5l_test_time.txt
  audio/3_class/cnn32_5l_train_time.txt
  audio/3_class/cnn32_test_time.txt
  audio/3_class/cnn32_train_time.txt
  audio/3_class/naive_rf.txt
  audio/3_class/naive_rf_test_time.txt
  audio/3_class/naive_rf_train_time.txt
  audio/3_class/resnet18.txt
  audio/3_class/resnet18_test_time.txt
  audio/3_class/resnet18_train_time.txt
  audio/3_class/svm.txt
  audio/3_class/svm_test_time.txt
  audio/3_class/svm_train_time.txt
  audio/8_class/cnn32.txt
  audio/8_class/cnn32_2l.txt
  audio/8_class/cnn32_2l_test_time.txt
  audio/8_class/cnn32_2l_train_time.txt
  audio/8_class/cnn32_5l.txt
  audio/8_class/cnn32_5l_test_time.txt
  audio/8_class/cnn32_5l_train_time.txt
  audio/8_class/cnn32_test_time.txt
  audio/8_class/cnn32_train_time.txt
  audio/8_class/naive_rf.txt
  audio/8_class/naive_rf_test_time.txt
  audio/8_class/naive_rf_train_time.txt
  audio/8_class/resnet18.txt
  audio/8_class/resnet18_test_time.txt
  audio/8_class/resnet18_train_time.txt
  audio/8_class/svm.txt
  audio/8_class/svm_test_time.txt
  audio/8_class/svm_train_time.txt
  audio/audio.py
  audio/audio_toolbox.py
  audio/fsdd_figure.ipynb
Labels: enhancement

#26 Audio figure update for fsdd
  audio/fsdd_figure.ipynb
Labels: bug

#27 Make cosmetic changes to CC18 figure and remove plots folder
  tabular/cc18_figures.ipynb
  tabular/plots/cc18_experiment.png
  tabular/plots/cc18_scatter_plot.png
Labels: enhancement

#28 Update image formats & organize figures
  audio/figures/mel.pdf
  audio/figures/mfcc.pdf
  audio/figures/spoken.pdf
  audio/fsdd_figures.ipynb
  image/cifar_figure.ipynb
  image/cifar_figures.ipynb
  image/figures/cifar.pdf
  image/figures/cifar_sc.pdf
  image/figures/cifar_st.pdf
  image/figures/svhn.pdf
  image/svhn_figure.ipynb
  tabular/cc18_figures.ipynb
  tabular/figures/cc18_experiment.pdf
Labels: documentation
